name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go-version: [ '1.19', '1.20', '1.21', '1.22', '1.23' ]

    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: ${{ matrix.go-version }}
        
    - name: Install dependencies
      run: go mod download
        
    - name: Build
      run: go build -v ./...
      
    - name: Test
      run: go test -v -race -coverprofile=coverage.txt -covermode=atomic ./...
      
    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v3
      with:
        file: ./coverage.txt
        
    - name: Run golangci-lint
      uses: golangci/golangci-lint-action@v3
      with:
        version: latest
        
  security:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    
    - name: Run Gosec Security Scanner
      uses: securego/gosec@master
      with:
        args: ./...
        # All security issues have been fixed:
        # - SQL injection vulnerabilities (G201) fixed by adding table name validation
        # - Path traversal vulnerabilities (G304) fixed by adding path validation
        # - Directory permissions issues (G301) fixed by using 0750 instead of 0755
        # - File permissions issues (G306) fixed by using 0600 instead of 0644
        # - Error handling issues (G104) fixed by properly checking and handling errors
        
    - name: Run dependency vulnerability scan
      uses: golang/govulncheck-action@v1 